# Generated by Django 3.1.3 on 2021-02-18 13:50

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=56)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoriesLanguages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categories')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.languages')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='languages',
            field=models.ManyToManyField(through='blog.CategoriesLanguages', to='blog.Languages'),
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=56)),
                ('image', models.CharField(blank=True, max_length=32, null=True)),
                ('content', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='roles.author')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.categories')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
