# Generated by Django 3.1.3 on 2021-02-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
