# Generated by Django 3.1.3 on 2021-02-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210218_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='category_id',
            new_name='category',
        ),
    ]
