# Generated by Django 3.1.3 on 2021-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='languages',
            field=models.ManyToManyField(to='blog.Languages'),
        ),
    ]
