# Generated by Django 3.1.3 on 2021-02-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210218_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='author_id',
            new_name='author',
        ),
    ]
