# Generated by Django 3.1.3 on 2021-02-19 13:39

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210218_1450'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['category', 'title'], name='blog_articl_categor_81f7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='articles',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='blog_articl_content_77405c_gin'),
        ),
    ]
