# Generated by Django 3.1.3 on 2021-02-17 14:50

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20210217_1344'),
        ('blog', '0004_categories_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=56, null=True)),
                ('image', models.CharField(max_length=32, null=True)),
                ('content', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('code', models.TextField(null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='roles.author')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.categories')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
