# Generated by Django 3.1.3 on 2021-02-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(default='title', max_length=56),
            preserve_default=False,
        ),
    ]
