# Generated by Django 3.1.3 on 2021-02-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210219_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['title'], 'verbose_name': 'Articles', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'ordering': ['name'], 'verbose_name': 'Languages', 'verbose_name_plural': 'Languages'},
        ),
    ]
