# Generated by Django 3.1.3 on 2021-03-05 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210225_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='categories',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='languages',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['uuid'], name='blog_articl_uuid_969d40_idx'),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['uuid'], name='blog_catego_uuid_700fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='languages',
            index=models.Index(fields=['uuid'], name='blog_langua_uuid_45f40f_idx'),
        ),
    ]
