# Generated by Django 3.1.3 on 2021-03-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210305_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, max_length=32, null=True, upload_to=''),
        ),
    ]
