# Generated by Django 3.1.3 on 2021-03-18 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210307_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='image',
            field=models.FileField(blank=True, max_length=132, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
