# Generated by Django 3.1.3 on 2021-02-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(blank=True, max_length=132, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='social',
            field=models.CharField(blank=True, max_length=132, null=True),
        ),
    ]
