# Generated by Django 3.1.3 on 2021-02-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20210224_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Authors', 'verbose_name_plural': 'Authors'},
        ),
    ]
